-- MySQL Script generated by MySQL Workbench
-- 03/19/17 22:41:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fotr_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fotr_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fotr_database` DEFAULT CHARACTER SET utf8 ;
USE `fotr_database` ;

-- -----------------------------------------------------
-- Table `fotr_database`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotr_database`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `image-one` VARCHAR(255) NOT NULL,
  `image-two` VARCHAR(255) NOT NULL,
  `background-image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fotr_database`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotr_database`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_profile_idx` (`profile_id` ASC),
  CONSTRAINT `fk_User_profile`
    FOREIGN KEY (`profile_id`)
    REFERENCES `fotr_database`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fotr_database`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotr_database`.`character` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(2048) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fotr_database`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotr_database`.`movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(2048) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fotr_database`.`user_has_friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotr_database`.`user_has_friend` (
  `user_id` INT NOT NULL,
  `user_friend_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_friend_id`),
  INDEX `fk_user_has_user_user2_idx` (`user_friend_id` ASC),
  INDEX `fk_user_has_user_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fotr_database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`user_friend_id`)
    REFERENCES `fotr_database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fotr_database`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotr_database`.`publication` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(1024) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_publication_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_publication_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fotr_database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
